Accept region and zone for cluster credentials
Currently the command `update-kubeconfig-with-credentials` throws errors:

```bash
ERROR: (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
```

As it requires a `zone` or `region` parameter which is never passed. This can be hacked to work via the following:

```yaml
      - gcp-gke/update-kubeconfig-with-credentials:
          perform-login: true
          install-kubectl: true
          cluster: "my-cluster --region $GOOGLE_COMPUTE_REGION"
```